# Setup
title:               'Optimal Estimation'
tagline:             'A Jekyll theme'
description:         'Personal Website'
url:                 http://optimalestimation.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ujjwal Gupta
  url:               https://linkedin.com/in/ugujjwal/
  email:             ujjwal@asu.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
