# Setup
title:               Optimal Estimation
tagline:             'Live. Collect Data. Optimize. Repeat'
description:         'A personal website'
url:                 http://optimalestiation.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ujjwal Gupta
  url:               https://www.linkedin.com/in/ugujjwal/
  email:             Ujjwal@asu.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
